import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Analyzes a 360 degree panoramic image using Gemini Vision.
 * 
 * @param base64Image The base64 encoded image string (without the data prefix).
 * @param mimeType The mime type of the image.
 * @returns Parsed AnalysisResult.
 */
export const analyze360Image = async (
  base64Image: string,
  mimeType: string
): Promise<AnalysisResult> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: `Analyze this 360-degree equirectangular panoramic image. 
            Provide a detailed description of the scene, list distinct key objects visible, and describe the overall atmosphere or mood.`,
          },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            description: {
              type: Type.STRING,
              description: "A comprehensive paragraph describing the entire scene.",
            },
            objects: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
              description: "A list of key objects or landmarks visible in the panorama.",
            },
            atmosphere: {
              type: Type.STRING,
              description: "The mood, lighting, and general feeling of the location.",
            },
          },
          required: ["description", "objects", "atmosphere"],
        },
      },
    });

    if (response.text) {
      return JSON.parse(response.text) as AnalysisResult;
    }
    throw new Error("No response text from Gemini.");
  } catch (error) {
    console.error("Gemini analysis failed:", error);
    throw error;
  }
};

/**
 * Generates an edited version of the image using Gemini Nano Banana (gemini-2.5-flash-image).
 * 
 * @param base64Image The base64 encoded snapshot with visual mask applied.
 * @param mimeType The mime type.
 * @param prompt User instruction.
 * @param maskColorName The name of the color used for masking (e.g., "red", "blue").
 * @returns Base64 string of the generated image.
 */
export const generateEditedImage = async (
  base64Image: string,
  mimeType: string,
  prompt: string,
  maskColorName: string = "red"
): Promise<string> => {
  try {
    // Simplified prompt to avoid potential 500 errors from complex system instructions on this model
    const finalPrompt = `This image contains a ${maskColorName} masked area. 
Replace the content in the ${maskColorName} area with: ${prompt}.
The result must be photorealistic and blend seamlessly with the surrounding 360-degree environment lighting and perspective.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: finalPrompt,
          },
        ],
      },
    });

    // Extract image from response parts
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return part.inlineData.data;
        }
      }
    }
    
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini image generation failed:", error);
    throw error;
  }
};

/**
 * Generates edits for multiple masked areas in a single pass.
 */
export const generateMultiEditImage = async (
  base64Image: string,
  mimeType: string,
  layerInstructions: { colorName: string; prompt: string }[]
): Promise<string> => {
  try {
    const instructions = layerInstructions
      .map(l => `- Area masked in ${l.colorName}: ${l.prompt}`)
      .join('\n');

    // Simplified prompt for stability
    const finalPrompt = `This image contains multiple masked areas in different colors.
Apply the following edits to the respective masked areas:
${instructions}
Ensure all edits are photorealistic, consistent with the scene's lighting, and strictly respect the mask boundaries.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: finalPrompt,
          },
        ],
      },
    });

    // Extract image from response parts
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return part.inlineData.data;
        }
      }
    }
    
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini multi-edit generation failed:", error);
    throw error;
  }
};

/**
 * Applies a global style transfer to the entire 360 image.
 */
export const generateStyledImage = async (
  base64Image: string,
  mimeType: string,
  stylePrompt: string
): Promise<string> => {
  try {
    const finalPrompt = `Apply a global style transformation to this 360-degree equirectangular panoramic image.
Style: ${stylePrompt}
The result must maintain the 360-degree equirectangular projection, perspective, and lighting consistency. 
The output should be a single, high-quality image that looks like the original scene but completely transformed into the requested style.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: finalPrompt,
          },
        ],
      },
    });

    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData && part.inlineData.data) {
          return part.inlineData.data;
        }
      }
    }
    
    throw new Error("No styled image generated by Gemini.");
  } catch (error) {
    console.error("Gemini style generation failed:", error);
    throw error;
  }
};

/**
 * Finds normalized coordinates [x, y] for specific objects in a 360 panorama.
 */
export const findObjectsInPanorama = async (
  base64Image: string,
  mimeType: string,
  objects: string[]
): Promise<{ object: string; x: number; y: number }[]> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: `In this 360-degree equirectangular image, find the center coordinates for the following objects: ${objects.join(", ")}.
Return the coordinates as normalized values from 0.0 to 1.0, where (0,0) is top-left and (1,1) is bottom-right.`,
          },
        ],
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              object: { type: Type.STRING },
              x: { type: Type.NUMBER, description: "Normalized X coordinate (0-1)" },
              y: { type: Type.NUMBER, description: "Normalized Y coordinate (0-1)" },
            },
            required: ["object", "x", "y"],
          },
        },
      },
    });

    if (response.text) {
      return JSON.parse(response.text);
    }
    return [];
  } catch (error) {
    console.error("Gemini object finding failed:", error);
    return [];
  }
};
